invoice/api/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^InvoiceSeries/$', InvoiceSeriesView.as_view(), name='InvoiceSeriesView'),
    url(r'^InvoiceSerials/$', InvoiceSerialsView.as_view(), name='InvoiceSerialsView'),
    url(r'^CreateSales/$', CreateSalesPostView.as_view(), name='CreateSalesPostView'),


]

invoice/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    # buyer

    url(r'^InvoiceSeriesListJson/$', InvoiceSeriesListJson.as_view(), name='InvoiceSeriesListJson'),
    url(r'^InvoiceCreatedByCashListJson/$', InvoiceCreatedByCashListJson.as_view(),
        name='InvoiceCreatedByCashListJson'),
    url(r'^InvoiceCreatedByCardListJson/$', InvoiceCreatedByCardListJson.as_view(),
        name='InvoiceCreatedByCardListJson'),
    url(r'^InvoiceCreatedByMixListJson/$', InvoiceCreatedByMixListJson.as_view(), name='InvoiceCreatedByMixListJson'),
    url(r'^InvoiceCreatedByCreditListJson/$', InvoiceCreatedByCreditListJson.as_view(),
        name='InvoiceCreatedByCreditListJson'),
    url(r'^CollectionListJson/$', CollectionListJson.as_view(), name='CollectionListJson'),
    url(r'^CashCollectionListJson/$', CashCollectionListJson.as_view(), name='CashCollectionListJson'),
    url(r'^StaffAdvanceListJson/$', StaffAdvanceListJson.as_view(), name='StaffAdvanceListJson'),
    url(r'^ReturnCollectionListJson/$', ReturnCollectionListJson.as_view(), name='ReturnCollectionListJson'),
    url(r'^CorrectCollectionListJson/$', CorrectCollectionListJson.as_view(), name='CorrectCollectionListJson'),
    url(r'^CommissionListJson/$', CommissionListJson.as_view(), name='CommissionListJson'),
    url(r'^ExpenseListJson/$', ExpenseListJson.as_view(), name='ExpenseListJson'),

    url(r'^new_index/$', new_index, name='new_index'),
    url(r'^$', index, name='index'),
    url(r'^get_invoice_series/$', get_invoice_series, name='get_invoice_series'),
    url(r'^get_invoice_series_load_more/$', get_invoice_series_load_more, name='get_invoice_series_load_more'),
    url(r'^create_invoice/$', create_invoice, name='create_invoice'),
    url(r'^edit_invoice/$', edit_invoice, name='edit_invoice'),
    url(r'^edit_invoice_mix/$', edit_invoice_mix, name='edit_invoice_mix'),
    url(r'^edit_collection/$', edit_collection, name='edit_collection'),
    url(r'^edit_collection_cash/$', edit_collection_cash, name='edit_collection_cash'),
    url(r'^delete_sale_api/$', delete_sale_api, name='delete_sale_api'),
    url(r'^delete_sale_api_mix/$', delete_sale_api_mix, name='delete_sale_api_mix'),
    url(r'^delete_collection_api/$', delete_collection_api, name='delete_collection_api'),
    url(r'^delete_cash_collection_api/$', delete_cash_collection_api, name='delete_cash_collection_api'),
    url(r'^generateInvoice/$', generate_serial_invoice_number, name='generate_serial_invoice_number'),

    url(r'^manage_invoice/$', invoice_list, name='manage_invoice'),
    url(r'^add_invoice_serial/$', add_invoice_serial, name='add_invoice_serial'),
    url(r'^edit_invoice_serial/$', edit_invoice_serial, name='edit_invoice_serial'),

    url(r'^invoice_report/$', invoice_report, name='invoice_report'),
    url(r'^generate_net_report/$', generate_net_report, name='generate_net_report'),
    url(r'^generate_net_report_admin/$', generate_net_report_admin, name='generate_net_report_admin'),
    url(r'^generate_net_report_credit_admin/$', generate_net_report_credit_admin, name='generate_net_report_credit_admin'),
    url(r'^generate_net_report_accountant/$', generate_net_report_accountant, name='generate_net_report_accountant'),
    url(r'^generate_monthly_report_admin/$', generate_monthly_report_admin, name='generate_monthly_report_admin'),
    url(r'^generate_monthly_report_staff_advance_admin/$', generate_monthly_report_staff_advance_admin, name='generate_monthly_report_staff_advance_admin'),
    url(r'^generate_collection_report_for_cashier/$', generate_collection_report_for_cashier, name='generate_collection_report_for_cashier'),

    url(r'^search_invoice/$', search_invoice, name='search_invoice'),
    url(r'^skipped_invoice/$', skipped_invoice, name='skipped_invoice'),
    url(r'^take_collection/$', take_collection, name='take_collection'),
    url(r'^take_cash_collection/$', take_cash_collection, name='take_cash_collection'),

    url(r'^get_today_collection_by_company/$', get_today_collection_by_company, name='get_today_collection_by_company'),
    url(r'^get_today_cash_collection_by_company/$', get_today_cash_collection_by_company,
        name='get_today_cash_collection_by_company'),
    url(r'^add_party_from_sales/$', add_party_from_sales, name='add_party_from_sales'),
    url(r'^get_buyer_list/$', get_buyer_list, name='get_buyer_list'),

    url(r'^change_password_for_sales_user/$', change_password_for_sales_user, name='change_password_for_sales_user'),
    url(r'^get_last_three_invoices/$', get_last_three_invoices, name='get_last_three_invoices'),
    url(r'^generate_collection_report_admin/$', generate_collection_report_admin,
        name='generate_collection_report_admin'),

    url(r'^generate_collection_report_accounts/$', generate_collection_report_accounts,
        name='generate_collection_report_accounts'),
    url(r'^generate_collection_report_supplier/$', generate_collection_report_supplier,
        name='generate_collection_report_supplier'),
    url(r'^generate_collection_report/$', generate_collection_report, name='generate_collection_report'),

    # Accountant
    url(r'^collection_report_accountant/$', collection_report_accountant, name='collection_report_accountant'),

    # Return
    url(r'^return_collection_post/$', return_collection, name='return_collection'),
    url(r'^get_today_return_by_company/$', get_today_return_by_company, name='get_today_return_by_company'),
    url(r'^edit_return/$', edit_return, name='edit_return'),
    url(r'^delete_return_api/$', delete_return_api, name='delete_return_api'),

    # Commission
    url(r'^commission_collection_post/$', commission_collection, name='commission_collection'),
    url(r'^get_today_commission_by_company/$', get_today_commission_by_company, name='get_today_commission_by_company'),
    url(r'^edit_commission/$', edit_commission, name='edit_commission'),
    url(r'^delete_commission_api/$', delete_commission_api, name='delete_commission_api'),

    # Correction
    url(r'^correction_collection_post/$', correct_collection, name='correct_collection'),
    url(r'^get_today_correction_by_company/$', get_today_correction_by_company, name='get_today_correction_by_company'),
    url(r'^edit_correction/$', edit_correction, name='edit_correction'),
    url(r'^delete_correction_api/$', delete_correction_api, name='delete_correction_api'),

    # expense
    url(r'^add_expense/$', add_expense, name='add_expense'),
    url(r'^get_today_expense_by_company/$', get_today_expense_by_company, name='get_today_expense_by_company'),
    url(r'^edit_expense/$', edit_expense, name='edit_expense'),
    url(r'^delete_expense_api/$', delete_expense_api, name='delete_expense_api'),

    url(r'^add_closing_balance_api/$', add_closing_balance_api, name='add_closing_balance_api'),

    # staffAdvance
    url(r'^staff_advance_post/$', staff_advance_post, name='staff_advance_post'),
    url(r'^get_today_staff_advance_by_company/$', get_today_staff_advance_by_company,
        name='get_today_staff_advance_by_company'),
    url(r'^edit_staff_advance/$', edit_staff_advance, name='edit_staff_advance'),
    url(r'^delete_staff_advance_api/$', delete_staff_advance_api, name='delete_staff_advance_api'),

    # Take order PDF
    url(r'^share_order_to_whatsapp_pdf/$', share_order_to_whatsapp_pdf, name='share_order_to_whatsapp_pdf'),
    url(r'^generate_order_report_admin/$', generate_order_report_admin, name='generate_order_report_admin'),
    url(r'^generate_order_report_manager/$', generate_order_report_manager, name='generate_order_report_manager'),

    url(r'^edit_invoice_by_accountant/$', edit_invoice_by_accountant, name='edit_invoice_by_accountant'),



]

mamtaPro/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("mamtaApp.urls", namespace='mamtaApp')),
    url(r'^invoice/', include("invoice.urls", namespace='invoiceApp')),
    url(r'^attendance/', include("attendance.urls", namespace='attendanceApp')),
    url(r'^api/', include('mamtaApp.api.urls')),
    url(r'^invoiceApi/', include('invoice.api.urls')),
    url(r'^docs/', include('rest_framework_docs.urls')),
    url('', include('pwa.urls')),
]
handler404 = 'mamtaApp.views.bad_request'
handler500 = 'mamtaApp.views.bad_server'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoice/api/views.py
from django.contrib.auth import authenticate
from django.http import JsonResponse
from rest_framework_jwt.serializers import JSONWebTokenSerializer, jwt_encode_handler, jwt_payload_handler
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from rest_framework.response import Response

from .serializers import *
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated, AllowAny

from rest_framework_jwt.settings import api_settings

jwt_decode_handler = api_settings.JWT_DECODE_HANDLER
from django.contrib.auth.models import Group
from invoice.models import *
from datetime import datetime, timedelta


class InvoiceSeriesView(APIView):
    '''
    {"message":"success","data":{
                    'Series':obj.series,
                    'SeriesID':obj.pk
                }}
    '''

    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        try:
            invoiceSerial = InvoiceSeries.objects.select_related().all().order_by('series')
            in_list = []
            for obj in invoiceSerial:
                in_dic = {
                    'Series': obj.series,
                    'SeriesID': obj.pk
                }

                in_list.append(in_dic)

            return Response({'message': 'success', 'data': in_list})
        except:
            return Response({'message': 'fail'})


class InvoiceSerialsView(APIView):
    '''
    {'data':{
            'Used':[{
                        'Serial':numbers.serials,
                        'SerialID':numbers.pk
                    }],
            'UnUsed':[{
                        'Serial':numbers.serials,
                        'SerialID':numbers.pk
                    }],
            'Upcoming': [{
                        'Serial':numbers.serials,
                        'SerialID':numbers.pk
                    }],
        

        }}
    '''

    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        invoiceByUser = InvoiceSeries.objects.select_related().get(assignedTo__userID_id=request.user.pk)

        salesID = Sales.objects.select_related().filter(invoiceSerialID__invoiceSeriesID_id=invoiceByUser.pk,
                                                        datetime__gte=datetime.today().date() - timedelta(
                                                            days=1)).order_by(
            '-invoiceSerialID')

        last_used_invoice_number = salesID.first()

        # used
        used_invoice_id_list = []
        un_used_invoice_id_list = []
        for numbers in InvoiceSerial.objects.select_related().filter(
                series__lt=last_used_invoice_number.invoiceSerialID.serials):
            for sale in salesID:
                if numbers.pk == sale.invoiceSerialID_id:

                    used_invoice_id_dic = {
                        'Serial': numbers.serials,
                        'SerialID': numbers.pk
                    }

                    used_invoice_id_list.append(used_invoice_id_dic)
                else:
                    un_used_invoice_id_dic = {
                        'Serial': numbers.serials,
                        'SerialID': numbers.pk
                    }

                    un_used_invoice_id_list.append(un_used_invoice_id_dic)
        upcoming_serials_invoice_id_list = []
        for obj in InvoiceSerial.objects.select_related().filter(
                series__gt=last_used_invoice_number.invoiceSerialID.serials):
            upcoming_serials_invoice_id_dic = {
                'Serial': obj.serials,
                'SerialID': obj.pk
            }

            upcoming_serials_invoice_id_list.append(upcoming_serials_invoice_id_dic)

        data = {
            'Used': used_invoice_id_list,
            'UnUsed': un_used_invoice_id_list,
            'Upcoming': upcoming_serials_invoice_id_list,

        }

        return Response({'data': data})


class CreateSalesPostView(APIView):
    serializer_class = CreateInvoiceSerializer
    permission_classes = [IsAuthenticated]

    def post(self, request):
        serializer = CreateInvoiceSerializer(data=request.data)
        if serializer.is_valid():
            InvoiceSerialID = request.data.get('InvoiceSerialID')
            BillNumber = request.data.get('BillNumber')
            SalesType = request.data.get('SalesType')
            Amount = request.data.get('Amount')
            CustomerName = request.data.get('CustomerName')

            sale = Sales()
            sale.invoiceSerialID_id = int(InvoiceSerialID)
            sale.billNumber = BillNumber
            sale.salesType = SalesType
            sale.amount = float(Amount)
            sale.customerName = CustomerName
            if SalesType == 'Cash':
                sale.isCash = True
            if SalesType == 'Cheque':
                sale.isCash = False

            user = StaffUser.objects.select_related().get(userID_id=request.user.pk)
            sale.createdBy_id = user.pk
            sale.save()
            return Response({'message': 'success'})
        else:
            return Response({'message': 'fail'})

invoice/templates/invoice/CashierCollectionPDFReport.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>123DACN</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <style>
        @page {
            size: A5;
            margin: .3cm;
        }

        section {
            columns: 1;
        }

        .skip {
            columns: 7;
        }

        table.table-bordered > thead > tr > th {
            border: 1px solid grey !important;
        }

        table.table-bordered > tbody > tr > td {
            border: 1px solid grey !important;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <span style="font-size: 10px;">Date: {{ date }}</span>
        <span style="font-size: 9px;float: right"> Collection Report -({{ user.name }})</span>
    </div>

     <p style="font-size: 10px; margin: 2px;">Collection<span
                style="float: right">Total: ₹ <strong>{{ total }}</strong></span></p>
    <section>
        <table class="table table-bordered" style="font-size: 9px;width: 100%">
            <thead>
            <tr>
                <th scope="col">Amount(₹)</th>
                <th scope="col">Party Name</th>
                <th scope="col">Payment Mode</th>
                <th scope="col">EntryOn</th>
                <th scope="col">Remark</th>
            </tr>
            </thead>
            <tbody>
            {% for foo in cashcollection %}
                <tr>
                    <td>{{ foo.amount }}</td>
                    <td>{{ foo.buyerID.name|truncatechars:20 }}</td>
                    <td>{{ foo.paymentMode }}</td>
                    <td>{{ foo.datetime|date:"Y-m-d H:i" }}</td>
                    <td><{{ foo.remark }}/td>

                </tr>
            {% endfor %}

              {% for foo in invoicecollection %}
                <tr>
                    <td>{{ foo.amount }}</td>
                    <td>{{ foo.buyerID.name|truncatechars:20 }}</td>
                    <td>Invoice</td>
                    <td>{{ foo.datetime|date:"Y-m-d H:i" }}</td>
                    <td><{{ foo.remark }}/td>

                </tr>
            {% endfor %}

            </tbody>
        </table>
    </section>
</div>
</body>
</html>

invoice/templates/invoice/OrderPDFManager.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>123DACN</title>
    <style>
        @page {
            size: A5;
            margin: .3cm;
        }

        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 5px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <span style="font-size: 10px;">Date: {{ date }}</span>
        <span style="font-size: 9px;float: right"> Order Report-({{ name }})</span>
    </div>

    <p style="font-size: 10px; margin: 2px;">Orders</p>
    <section>
        <table class="table table-bordered" style="font-size: 9px;">
            <thead>
            <tr>
                <th scope="col">OrderTiming</th>
                <th scope="col">Location</th>
                <th scope="col">PartyName</th>
                <th scope="col">VisitType</th>
                <th scope="col">OperatorName</th>
            </tr>
            </thead>
            <tbody>
            {% for foo in col %}
                <tr>
                    <td>{{ foo.datetime|time:'h:i A'  }}</td>
                    <td>{{ foo.location }}</td>
                    <td>{{ foo.partyName }}</td>
                    <td>{{ foo.orderTakenFrom }}</td>
                    <td>{{ foo.orderTakenBy }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </section>

</div>
</body>
</html>

invoice/templates/invoice/collectionPDF.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>123DACN</title>
    <style>
        @page {
            size: A5;
            margin: .3cm;
        }

        section {
            columns: 2;
        }

        .skip {
            columns: 7;
        }

       table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 5px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <span style="font-size: 10px;">Date: {{ date }}</span>
        <span style="font-size: 9px;float: right"> Collection Report -({{ user.companyID.name }})</span>
    </div>
{#    <p style="font-size: 10px; margin: 2px;">Collection</p>#}
{#    <section>#}
{#        <table class="table table-bordered" style="font-size: 9px;">#}
{#            <thead>#}
{#            <tr>#}
{#                <th scope="col">Amount(₹)</th>#}
{#                <th scope="col">Cus_Name</th>#}
{#                <th scope="col">Remark</th>#}
{#            </tr>#}
{#            </thead>#}
{#            <tbody>#}
{#            {% for foo in col %}#}
{#                <tr>#}
{#                    <td>{{ foo.amount }}</td>#}
{#                    <td>{{ foo.buyerID.name|truncatechars:20 }}</td>#}
{#                    <td>{{ foo.remark }}</td>#}
{##}
{#                </tr>#}
{#            {% endfor %}#}
{##}
{#            </tbody>#}
{#        </table>#}
{#    </section>#}
    <p style="font-size: 10px; margin: 2px;">CC</p>
    <section>
        <table class="table table-bordered" style="font-size: 9px;">
            <thead>
            <tr>
                <th scope="col">Amount(₹)</th>
                <th scope="col">Cus_Name</th>
                <th scope="col">EntryOn</th>
                <th scope="col">Remark</th>
            </tr>
            </thead>
            <tbody>
            {% for foo in colCash %}
                <tr>
                    <td>{{ foo.amount }}</td>
                    <td>{{ foo.buyerID.name|truncatechars:20 }}</td>
                    <td>{{ foo.datetime|date:"Y-m-d H:i" }}</td>
                    <td></td>

                </tr>
            {% endfor %}

            </tbody>
        </table>
    </section>
</div>
</body>
</html>

invoice/templates/invoice/manageInvoice.html
{% extends 'mamtaApp/index.html' %}
{% load staticfiles %}
{% block body %}
    <style>
        .card {
            background: #fff;
            min-height: 50px;
            box-shadow: 0 0px 0px rgba(0, 0, 0, 0) !important;
            position: relative;
            margin-bottom: 30px;
            -webkit-border-radius: 2px;
            -moz-border-radius: 2px;
            -ms-border-radius: 2px;
            border-radius: 2px;
        }

        .dt-buttons {
            padding-top: 10px;
        }

        .hidePadding {
            padding-left: 0 !important;
            padding-right: 0 !important;
        }
    </style>
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">

                <div style="float: right">
                    {% if request.user|has_group:"Admin" %}

                        <button style="background-color: #3F51B5;color: white;margin-bottom: 10px" type="button"
                                class="btn  waves-effect " data-toggle="modal" data-target="#defaultModal">Add Invoice
                            Serial
                        </button>
                    {% endif %}
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 hidePadding">
                    <div class="card">

                        <div class="header">
                            <h2>
                                INVOICE SERIAL LIST
                            </h2>

                        </div>

                        <div class="body">
                            <div class="table-responsive">
                                <table id="buyerCreditTable" class="table table-bordered table-striped table-hover">
                                    <thead>
                                    <tr>
                                        <th>Sl. No</th>
                                        <th>Series</th>
                                        <th>Company</th>
                                    </tr>
                                    </thead>
                                    <tfoot>
                                    <tr>
                                        <th>Sl. No</th>
                                        <th>Series</th>
                                        <th>Company</th>

                                    </tr>
                                    </tfoot>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="modal fade" id="defaultModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="defaultModalLabel">Add Invoice Serial</h4>
                </div>
                <div class="modal-body">
                    <form action="{% url 'invoiceApp:add_invoice_serial' %}" id="AddCreditForm"
                          method="post"> {% csrf_token %}
                        <div class="row clearfix">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="card">
                                    <div class="body">

                                        <div class="row clearfix">
                                            <div class="col-md-12 col-sm-12">
                                                <div class="input-group">
                                        <span class="input-group-addon">
                                        <i class="material-icons">location_city</i>
                                        </span>
                                                    <div class="form-line">
                                                        <select class="form-control show-tick" id="companyID"
                                                                name="companyID">
                                                            <option value="all">Select Company</option>
                                                            {% for comp in company %}
                                                                <option value="{{ comp.pk }}">{{ comp.name }}</option>
                                                            {% endfor %}
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row clearfix">
                                            <div class="col-md-12">
                                                <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="material-icons">receipt</i>
                                        </span>
                                                    <div class="form-line">
                                                        <input type="text" class="form-control date"
                                                               placeholder="Invoice Series Number" name="invoiceSeries"
                                                               id="invoiceSeries">
                                                    </div>
                                                </div>
                                            </div>

                                        </div>


                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link waves-effect" onclick="AddCredit()">Submit</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="defaultModalEdit" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="defaultModalLabel">Edit Invoice Serial</h4>
                </div>
                <div class="modal-body">
                    <form action="{% url 'invoiceApp:edit_invoice_serial' %}" id="EditCreditForm"
                          method="post"> {% csrf_token %}
                        <div class="row clearfix">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="card">
                                    <input type="hidden" id="invoiceID" name="invoiceID">

                                    <div class="body">

                                        <div class="row clearfix">
                                        </div>
                                        <div class="row clearfix">
                                            <div class="col-md-12">
                                                <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="material-icons">receipt</i>
                                        </span>
                                                    <div class="form-line">
                                                        <input type="text" class="form-control date"
                                                               placeholder="Invoice Series Number" name="einvoiceSeries"
                                                               id="einvoiceSeries">
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link waves-effect" onclick="EditInvoice()">Submit</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        $(document).ready(function () {
            $('#buyerCreditTable').dataTable({
                dom: 'Blfrtip',
                buttons: ['excel', 'print'
                ],
                "columnDefs": [
                    {"name": "id", "targets": 0, "orderable": false},
                    {"name": "series", "targets": 1, "orderable": true},
                    {"name": "companyID", "targets": 2, "orderable": true},
                    {#                    {"name": "action", "targets": 2, "orderable": false},#}

                ],
                aaSorting: [[1, 'asc']],
                "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                "pageLength": 10,
                "processing": true,
                "serverSide": true,
                "ajax": "{% url 'invoiceApp:InvoiceSeriesListJson' %}"
            });
        });


    </script>
    <script>
        function AddCredit() {
            var invoiceSeries = $('#invoiceSeries').val();
            var companyID = $('#companyID').val();


            if (invoiceSeries === "" || companyID === "all") {
                $('#name_status').addClass('validate_data');
                $('#name_status').html('* fields are required.');
                $('#name_status').fadeIn().fadeOut(2000);

            }
            else {

                $('#AddCreditForm').submit();

            }


        }
        function EditInvoice() {
            {#            var buyerID = $('#ebuyerID').val();#}
            var invoiceSeries = $('#einvoiceSeries').val();


            if (invoiceSeries === "") {
                $('#name_status').addClass('validate_data');
                $('#name_status').html('* fields are required.');
                $('#name_status').fadeIn().fadeOut(2000);

            }
            else {

                $('#EditCreditForm').submit();

            }


        }
        function getDetail(id, series) {
            $('#invoiceID').val(id);
            $('#einvoiceSeries').val(series);


        }
    </script>
{% endblock %}