attendance/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    # buyer
    url(r'^LoginSystemListJson/$', LoginSystemListJson.as_view(), name='LoginSystemListJson'),
    url(r'^EmployeeListJson/$', EmployeeListJson.as_view(), name='EmployeeListJson'),
    url(r'^EmployeeListForAttendanceJson/$', EmployeeListForAttendanceJson.as_view(), name='EmployeeListForAttendanceJson'),
    url(r'^EmployeeListForAttendanceAdminJson/$', EmployeeListForAttendanceAdminJson.as_view(), name='EmployeeListForAttendanceAdminJson'),
    url(r'^EmployeeListForAttendanceAdminBasicJson/$', EmployeeListForAttendanceAdminBasicJson.as_view(), name='EmployeeListForAttendanceAdminBasicJson'),
    url(r'^OrderEmployeeListForAttendanceAdminBasicJson/$', OrderEmployeeListForAttendanceAdminBasicJson.as_view(), name='OrderEmployeeListForAttendanceAdminBasicJson'),

    url(r'^attendance/$', attendance, name='attendance'),
    url(r'^attendanceReport/$', attendanceReport, name='attendanceReport'),


    url(r'^ManageLoginSystem/$', loginSystem, name='loginSystem'),
    url(r'^add_login_system_api/$', add_login_system_api, name='add_login_system_api'),
    url(r'^edit_login_system_api/$', edit_login_system_api, name='edit_login_system_api'),


    url(r'^manageEmployee/$', manageEmployee, name='manageEmployee'),
    url(r'^addEmployee/$', addEmployee, name='addEmployee'),
    url(r'^employee/edit/(?P<id>\d+)/$', edit_employee, name='edit_employee'),

    url(r'^add_employee_api/$', add_employee_api, name='add_employee_api'),
    url(r'^edit_employee_api/$', edit_employee_api, name='edit_employee_api'),
    url(r'^edit_employee_photo_api/$', edit_employee_photo_api, name='edit_employee_photo_api'),
    url(r'^delete_employee_api/$', delete_employee_api, name='delete_employee_api'),



    url(r'^login_post_api/$', login_post_api, name='login_post_api'),
    url(r'^logout_post_api/$', logout_post_api, name='logout_post_api'),
    url(r'^genereate_attendence_report/$', genereate_attendence_report, name='genereate_attendence_report'),
    url(r'^demoReport/$', demoReport, name='demoReport'),
    url(r'^order_employee_attendance_post_api/$', order_employee_attendance_post_api, name='order_employee_attendance_post_api'),
    url(r'^generate_attendance_for_order_emp_report/$', generate_attendance_for_order_emp_report, name='generate_attendance_for_order_emp_report'),

]

invoice/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    # buyer

    url(r'^InvoiceSeriesListJson/$', InvoiceSeriesListJson.as_view(), name='InvoiceSeriesListJson'),
    url(r'^InvoiceCreatedByCashListJson/$', InvoiceCreatedByCashListJson.as_view(),
        name='InvoiceCreatedByCashListJson'),
    url(r'^InvoiceCreatedByCardListJson/$', InvoiceCreatedByCardListJson.as_view(),
        name='InvoiceCreatedByCardListJson'),
    url(r'^InvoiceCreatedByMixListJson/$', InvoiceCreatedByMixListJson.as_view(), name='InvoiceCreatedByMixListJson'),
    url(r'^InvoiceCreatedByCreditListJson/$', InvoiceCreatedByCreditListJson.as_view(),
        name='InvoiceCreatedByCreditListJson'),
    url(r'^CollectionListJson/$', CollectionListJson.as_view(), name='CollectionListJson'),
    url(r'^CashCollectionListJson/$', CashCollectionListJson.as_view(), name='CashCollectionListJson'),
    url(r'^StaffAdvanceListJson/$', StaffAdvanceListJson.as_view(), name='StaffAdvanceListJson'),
    url(r'^ReturnCollectionListJson/$', ReturnCollectionListJson.as_view(), name='ReturnCollectionListJson'),
    url(r'^CorrectCollectionListJson/$', CorrectCollectionListJson.as_view(), name='CorrectCollectionListJson'),
    url(r'^CommissionListJson/$', CommissionListJson.as_view(), name='CommissionListJson'),
    url(r'^ExpenseListJson/$', ExpenseListJson.as_view(), name='ExpenseListJson'),

    url(r'^new_index/$', new_index, name='new_index'),
    url(r'^$', index, name='index'),
    url(r'^get_invoice_series/$', get_invoice_series, name='get_invoice_series'),
    url(r'^get_invoice_series_load_more/$', get_invoice_series_load_more, name='get_invoice_series_load_more'),
    url(r'^create_invoice/$', create_invoice, name='create_invoice'),
    url(r'^edit_invoice/$', edit_invoice, name='edit_invoice'),
    url(r'^edit_invoice_mix/$', edit_invoice_mix, name='edit_invoice_mix'),
    url(r'^edit_collection/$', edit_collection, name='edit_collection'),
    url(r'^edit_collection_cash/$', edit_collection_cash, name='edit_collection_cash'),
    url(r'^delete_sale_api/$', delete_sale_api, name='delete_sale_api'),
    url(r'^delete_sale_api_mix/$', delete_sale_api_mix, name='delete_sale_api_mix'),
    url(r'^delete_collection_api/$', delete_collection_api, name='delete_collection_api'),
    url(r'^delete_cash_collection_api/$', delete_cash_collection_api, name='delete_cash_collection_api'),
    url(r'^generateInvoice/$', generate_serial_invoice_number, name='generate_serial_invoice_number'),

    url(r'^manage_invoice/$', invoice_list, name='manage_invoice'),
    url(r'^add_invoice_serial/$', add_invoice_serial, name='add_invoice_serial'),
    url(r'^edit_invoice_serial/$', edit_invoice_serial, name='edit_invoice_serial'),

    url(r'^invoice_report/$', invoice_report, name='invoice_report'),
    url(r'^generate_net_report/$', generate_net_report, name='generate_net_report'),
    url(r'^generate_net_report_admin/$', generate_net_report_admin, name='generate_net_report_admin'),
    url(r'^generate_net_report_credit_admin/$', generate_net_report_credit_admin, name='generate_net_report_credit_admin'),
    url(r'^generate_net_report_accountant/$', generate_net_report_accountant, name='generate_net_report_accountant'),
    url(r'^generate_monthly_report_admin/$', generate_monthly_report_admin, name='generate_monthly_report_admin'),
    url(r'^generate_monthly_report_staff_advance_admin/$', generate_monthly_report_staff_advance_admin, name='generate_monthly_report_staff_advance_admin'),
    url(r'^generate_collection_report_for_cashier/$', generate_collection_report_for_cashier, name='generate_collection_report_for_cashier'),

    url(r'^search_invoice/$', search_invoice, name='search_invoice'),
    url(r'^skipped_invoice/$', skipped_invoice, name='skipped_invoice'),
    url(r'^take_collection/$', take_collection, name='take_collection'),
    url(r'^take_cash_collection/$', take_cash_collection, name='take_cash_collection'),

    url(r'^get_today_collection_by_company/$', get_today_collection_by_company, name='get_today_collection_by_company'),
    url(r'^get_today_cash_collection_by_company/$', get_today_cash_collection_by_company,
        name='get_today_cash_collection_by_company'),
    url(r'^add_party_from_sales/$', add_party_from_sales, name='add_party_from_sales'),
    url(r'^get_buyer_list/$', get_buyer_list, name='get_buyer_list'),

    url(r'^change_password_for_sales_user/$', change_password_for_sales_user, name='change_password_for_sales_user'),
    url(r'^get_last_three_invoices/$', get_last_three_invoices, name='get_last_three_invoices'),
    url(r'^generate_collection_report_admin/$', generate_collection_report_admin,
        name='generate_collection_report_admin'),

    url(r'^generate_collection_report_accounts/$', generate_collection_report_accounts,
        name='generate_collection_report_accounts'),
    url(r'^generate_collection_report_supplier/$', generate_collection_report_supplier,
        name='generate_collection_report_supplier'),
    url(r'^generate_collection_report/$', generate_collection_report, name='generate_collection_report'),

    # Accountant
    url(r'^collection_report_accountant/$', collection_report_accountant, name='collection_report_accountant'),

    # Return
    url(r'^return_collection_post/$', return_collection, name='return_collection'),
    url(r'^get_today_return_by_company/$', get_today_return_by_company, name='get_today_return_by_company'),
    url(r'^edit_return/$', edit_return, name='edit_return'),
    url(r'^delete_return_api/$', delete_return_api, name='delete_return_api'),

    # Commission
    url(r'^commission_collection_post/$', commission_collection, name='commission_collection'),
    url(r'^get_today_commission_by_company/$', get_today_commission_by_company, name='get_today_commission_by_company'),
    url(r'^edit_commission/$', edit_commission, name='edit_commission'),
    url(r'^delete_commission_api/$', delete_commission_api, name='delete_commission_api'),

    # Correction
    url(r'^correction_collection_post/$', correct_collection, name='correct_collection'),
    url(r'^get_today_correction_by_company/$', get_today_correction_by_company, name='get_today_correction_by_company'),
    url(r'^edit_correction/$', edit_correction, name='edit_correction'),
    url(r'^delete_correction_api/$', delete_correction_api, name='delete_correction_api'),

    # expense
    url(r'^add_expense/$', add_expense, name='add_expense'),
    url(r'^get_today_expense_by_company/$', get_today_expense_by_company, name='get_today_expense_by_company'),
    url(r'^edit_expense/$', edit_expense, name='edit_expense'),
    url(r'^delete_expense_api/$', delete_expense_api, name='delete_expense_api'),

    url(r'^add_closing_balance_api/$', add_closing_balance_api, name='add_closing_balance_api'),

    # staffAdvance
    url(r'^staff_advance_post/$', staff_advance_post, name='staff_advance_post'),
    url(r'^get_today_staff_advance_by_company/$', get_today_staff_advance_by_company,
        name='get_today_staff_advance_by_company'),
    url(r'^edit_staff_advance/$', edit_staff_advance, name='edit_staff_advance'),
    url(r'^delete_staff_advance_api/$', delete_staff_advance_api, name='delete_staff_advance_api'),

    # Take order PDF
    url(r'^share_order_to_whatsapp_pdf/$', share_order_to_whatsapp_pdf, name='share_order_to_whatsapp_pdf'),
    url(r'^generate_order_report_admin/$', generate_order_report_admin, name='generate_order_report_admin'),
    url(r'^generate_order_report_manager/$', generate_order_report_manager, name='generate_order_report_manager'),

    url(r'^edit_invoice_by_accountant/$', edit_invoice_by_accountant, name='edit_invoice_by_accountant'),



]

mamtaPro/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("mamtaApp.urls", namespace='mamtaApp')),
    url(r'^invoice/', include("invoice.urls", namespace='invoiceApp')),
    url(r'^attendance/', include("attendance.urls", namespace='attendanceApp')),
    url(r'^api/', include('mamtaApp.api.urls')),
    url(r'^invoiceApi/', include('invoice.api.urls')),
    url(r'^docs/', include('rest_framework_docs.urls')),
    url('', include('pwa.urls')),
]
handler404 = 'mamtaApp.views.bad_request'
handler500 = 'mamtaApp.views.bad_server'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/models.py
from django.db import models
from django.contrib.auth.models import User
from stdimage import StdImageField
from datetime import time

# Create your models here.

class LoginSystem(models.Model):
    systemName = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    username = models.CharField(max_length=100, blank=True, null=True)
    password = models.CharField(max_length=100, blank=True, null=True)
    userID = models.ForeignKey(User, blank=True, null=True)
    isDeleted = models.BooleanField(default=False)
    datetime = models.DateTimeField(auto_now_add=True, auto_now=False)
    lastUpdatedOn = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.systemName


class Employee(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    phoneNumber = models.CharField(max_length=100, blank=True, null=True)
    photo = StdImageField(upload_to='Employee', blank=True, null=True,
                          variations={'thumbnail': {'width': 70, 'height': 70}})
    inTime = models.TimeField(null=True)
    outTime = models.TimeField(null=True)
    # only hh:mm format
    maxInTime = models.TimeField(default=time(10, 15))
    maxOutTime = models.TimeField(default=time(20, 0))
    isActive = models.BooleanField(default=True)
    password = models.CharField(max_length=100, blank=True, null=True)
    isDeleted = models.BooleanField(default=False)
    datetime = models.DateTimeField(auto_now_add=True, auto_now=False)
    lastUpdatedOn = models.DateTimeField(auto_now_add=False, auto_now=True)
    autogenerated = models.BooleanField(default=False)
    staffIdIfAutogenerated = models.CharField(max_length=100, blank=True, null=True, default='N/A')


    def __str__(self):
        return self.name


class EmployeeAttendance(models.Model):
    employeeID = models.ForeignKey(Employee, blank=True, null=True)
    attendanceDate = models.DateField(null=True)
    loginTime = models.TimeField(null=True)
    loginRemark = models.CharField(max_length=500, blank=True, null=True)
    loginPhoto = StdImageField(upload_to='EmployeeAttendanceLogin', blank=True, null=True,
                               variations={'thumbnail': {'width': 70, 'height': 70}})

    logoutTime = models.TimeField(null=True)
    logoutRemark = models.CharField(max_length=500, blank=True, null=True)
    logoutPhoto = StdImageField(upload_to='EmployeeAttendanceLogout', blank=True, null=True,
                                variations={'thumbnail': {'width': 70, 'height': 70}})

    isDeleted = models.BooleanField(default=False)
    datetime = models.DateTimeField(auto_now_add=True, auto_now=False)
    lastUpdatedOn = models.DateTimeField(auto_now_add=False, auto_now=True)

    loginSystemID = models.ForeignKey(User, blank=True, null=True, related_name='login')
    logoutSystemID = models.ForeignKey(User, blank=True, null=True, related_name='logout')
    inLocation = models.TextField(max_length=1500, blank=True, null=True, default='N/A')
    outLocation = models.TextField(max_length=1500, blank=True, null=True, default='N/A')


    def __str__(self):
        return self.employeeID.name

attendance/templates/attendance/EmployeeList.html
{% extends 'mamtaApp/index.html' %}
{% load staticfiles %}
{% block body %}
  <style>
        .zoom {

            transition: transform .2s; /* Animation */
            width: 30px;
            height: 30px;
            margin: 0 auto;
        }

        .zoom:hover {
            transform: scale(4); /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
        }

        .card {
            background: #fff;
            min-height: 50px;
            box-shadow: 0 0px 0px rgba(0, 0, 0, 0) !important;
            position: relative;
            margin-bottom: 30px;
            -webkit-border-radius: 2px;
            -moz-border-radius: 2px;
            -ms-border-radius: 2px;
            border-radius: 2px;
        }

    </style>

    <style>
        .avatar-upload {
            position: relative;
            max-width: 205px;
            margin: 50px auto;
        }

        .avatar-upload .avatar-edit {
            position: absolute;
            right: 12px;
            z-index: 1;
            top: 10px;
        }

        .avatar-upload .avatar-edit input {
            display: none;
        }

    .dt-buttons {
            padding-top: 10px;
        }
    .hidePadding{
        padding-left: 0!important;
        padding-right: 0!important;
    }
    </style>
<section class="content">
        {% if request.user|has_group:"Moderator" %}

        {% endif %}
        <div class="container-fluid">
            <div style="float: right">
                {% if not request.user|has_group:"Moderator" %}

                    <a style="background-color: #3F51B5;color: white;margin-bottom: 10px" type="button"
                       href="{% url 'attendanceApp:addEmployee' %}"
                       class="btn  waves-effect ">Add New Employee
                    </a>
                {% endif %}
            </div>
            <!-- Striped Rows -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="padding-right: 0;padding-left: 0">
                    <div class="card">
                        <div class="header">
                            <h2>
                                EMPLOYEE LIST
                            </h2>
                        </div>
                        <div class="body table-responsive">
                            <table id="buyerCreditTable" class="table table-bordered table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Photo</th>
                                    <th>Name</th>
                                    <th>Number</th>
                                    <th>Address</th>
                                    <th>Password</th>
                                    <th>InTime</th>
                                    <th>OutTime</th>
                                    <th>LimitInTime</th>
                                    <th>AddedOn</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>

                                </tbody>
                                  <tfoot>
                                     <tr>
                                     <th>#</th>
                                    <th>Photo</th>
                                    <th>Name</th>
                                    <th>Number</th>
                                    <th>Address</th>
                                    <th>Password</th>
                                    <th>InTime</th>
                                    <th>OutTime</th>
                                    <th>LimitInTime</th>
                                    <th>AddedOn</th>
                                    <th>Action</th>
                                </tr>
                                    </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Striped Rows -->
        </div>
    </section>
    <div class="modal fade" id="defaultModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="{% url 'attendanceApp:delete_employee_api' %}" id="DeleteStaffForm"
                      method="post">{% csrf_token %}
                    <input type="hidden" name="userID" id="userID">
                    <div class="modal-header">
                        <h4 class="modal-title" id="defaultModalLabel">Confirm</h4>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to delete this data?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-link waves-effect" onclick="deleteStaff()">Yes</button>
                        <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">No</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
<script src="{% static 'js/pages/ui/modals.js' %}"></script>
    <script>

        function getStaffID(id) {
            $('#userID').val(id)

        }
        function deleteStaff() {
            $('#DeleteStaffForm').submit();

        }
    </script>
    <script>
        $(document).ready(function () {
            $('#buyerCreditTable').dataTable({
                dom: 'Blfrtip',
                buttons: ['excel', 'print'
                ],
                "columnDefs": [
                    {"name": "id", "targets": 0, "orderable": false},
                    {"name": "photo", "targets": 1, "orderable": true},
                    {"name": "name", "targets": 2, "orderable": true},
                    {"name": "phoneNumber", "targets": 3, "orderable": true},
                    {"name": "address", "targets": 4, "orderable": true},
                    {"name": "password", "targets": 5, "orderable": true},
                    {"name": "inTime", "targets": 6, "orderable": true},
                    {"name": "outTime", "targets": 7, "orderable": true},
                    {"name": "maxInTime", "targets": 8, "orderable": true},
                    {"name": "datetime", "targets": 9, "orderable": true},
                    {"name": "action", "targets": 10, "orderable": false},

                ],
                aaSorting: [[2, 'asc']],
                "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                "pageLength": 10,
                "processing": true,
                "serverSide": true,
                "ajax": "{% url 'attendanceApp:EmployeeListJson' %}"
            });
        });


    </script>
{% endblock %}

attendance/templates/attendance/attendancePDFreport.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>123DACN</title>
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">-->
    <style>
        @page {
            size: A4 landscape;
            margin: .1cm;
        }

        section {
            columns: 1;
        }

        .skip {
            columns: 7;
        }
        /* Style the entire table */
table {
    width: 100%; /* Make table fill the width of its container */
    border-collapse: collapse; /* Collapse borders into a single line */
    border: 1px solid lightgrey; /* Add a border to the table */
    margin: 20px 0; /* Add some margin around the table */
}

/* Style table headers */
th {
    background-color: #f9f9f9; /* Light grey background for headers */
    text-align: left; /* Align text to the left */
    padding: 8px; /* Padding inside the cells */
    border: 1px solid lightgrey; /* Add border to header cells */
}

/* Style table cells */
td {
    padding: 8px; /* Padding inside the cells */
    border: 1px solid lightgrey; /* Add border to table cells */
    text-align: left; /* Align text to the left */
}

/* Optional: Add hover effect for table rows */
tr:hover {
    background-color: #f1f1f1; /* Change background color on hover */
}
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <span style="font-size: 10px;">Generated On: {{ today|date }}</span>
    </div>

</div>

    <p style="font-size: 10px; margin: 2px;">For {{ Month }}</p>
    <section>
        <table class="table table-bordered" style="font-size: 8px;">
            <thead>
            <tr>
                <th scope="col">Name</th>
                {% for foo in days %}
                    <th scope="col">{{ forloop.counter }}</th>
                {% endfor %}
                <th scope="col">P's</th>
                <th scope="col">HD's</th>
                <th scope="col">A's</th>
                <th scope="col">H's</th>
            </tr>
            </thead>

            <tbody>
            {% for e in data %}
                <tr>
                    <td>{{ e.Name|truncatechars:12 }}</td>
                    {% for aa in e.attendance %}
                        <td>{{ aa }}</td>
                    {% endfor %}
                    <td>{{ e.P }}</td>
                    <td>{{ e.HD }}</td>
                    <td>{{ e.A }}</td>
                    <td>{{ e.NA }}</td>
                </tr>
            {% endfor %}

            </tbody>

        </table>
    </section>

</body>
</html>