invoice/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    # buyer

    url(r'^InvoiceSeriesListJson/$', InvoiceSeriesListJson.as_view(), name='InvoiceSeriesListJson'),
    url(r'^InvoiceCreatedByCashListJson/$', InvoiceCreatedByCashListJson.as_view(),
        name='InvoiceCreatedByCashListJson'),
    url(r'^InvoiceCreatedByCardListJson/$', InvoiceCreatedByCardListJson.as_view(),
        name='InvoiceCreatedByCardListJson'),
    url(r'^InvoiceCreatedByMixListJson/$', InvoiceCreatedByMixListJson.as_view(), name='InvoiceCreatedByMixListJson'),
    url(r'^InvoiceCreatedByCreditListJson/$', InvoiceCreatedByCreditListJson.as_view(),
        name='InvoiceCreatedByCreditListJson'),
    url(r'^CollectionListJson/$', CollectionListJson.as_view(), name='CollectionListJson'),
    url(r'^CashCollectionListJson/$', CashCollectionListJson.as_view(), name='CashCollectionListJson'),
    url(r'^StaffAdvanceListJson/$', StaffAdvanceListJson.as_view(), name='StaffAdvanceListJson'),
    url(r'^ReturnCollectionListJson/$', ReturnCollectionListJson.as_view(), name='ReturnCollectionListJson'),
    url(r'^CorrectCollectionListJson/$', CorrectCollectionListJson.as_view(), name='CorrectCollectionListJson'),
    url(r'^CommissionListJson/$', CommissionListJson.as_view(), name='CommissionListJson'),
    url(r'^ExpenseListJson/$', ExpenseListJson.as_view(), name='ExpenseListJson'),

    url(r'^new_index/$', new_index, name='new_index'),
    url(r'^$', index, name='index'),
    url(r'^get_invoice_series/$', get_invoice_series, name='get_invoice_series'),
    url(r'^get_invoice_series_load_more/$', get_invoice_series_load_more, name='get_invoice_series_load_more'),
    url(r'^create_invoice/$', create_invoice, name='create_invoice'),
    url(r'^edit_invoice/$', edit_invoice, name='edit_invoice'),
    url(r'^edit_invoice_mix/$', edit_invoice_mix, name='edit_invoice_mix'),
    url(r'^edit_collection/$', edit_collection, name='edit_collection'),
    url(r'^edit_collection_cash/$', edit_collection_cash, name='edit_collection_cash'),
    url(r'^delete_sale_api/$', delete_sale_api, name='delete_sale_api'),
    url(r'^delete_sale_api_mix/$', delete_sale_api_mix, name='delete_sale_api_mix'),
    url(r'^delete_collection_api/$', delete_collection_api, name='delete_collection_api'),
    url(r'^delete_cash_collection_api/$', delete_cash_collection_api, name='delete_cash_collection_api'),
    url(r'^generateInvoice/$', generate_serial_invoice_number, name='generate_serial_invoice_number'),

    url(r'^manage_invoice/$', invoice_list, name='manage_invoice'),
    url(r'^add_invoice_serial/$', add_invoice_serial, name='add_invoice_serial'),
    url(r'^edit_invoice_serial/$', edit_invoice_serial, name='edit_invoice_serial'),

    url(r'^invoice_report/$', invoice_report, name='invoice_report'),
    url(r'^generate_net_report/$', generate_net_report, name='generate_net_report'),
    url(r'^generate_net_report_admin/$', generate_net_report_admin, name='generate_net_report_admin'),
    url(r'^generate_net_report_credit_admin/$', generate_net_report_credit_admin, name='generate_net_report_credit_admin'),
    url(r'^generate_net_report_accountant/$', generate_net_report_accountant, name='generate_net_report_accountant'),
    url(r'^generate_monthly_report_admin/$', generate_monthly_report_admin, name='generate_monthly_report_admin'),
    url(r'^generate_monthly_report_staff_advance_admin/$', generate_monthly_report_staff_advance_admin, name='generate_monthly_report_staff_advance_admin'),
    url(r'^generate_collection_report_for_cashier/$', generate_collection_report_for_cashier, name='generate_collection_report_for_cashier'),

    url(r'^search_invoice/$', search_invoice, name='search_invoice'),
    url(r'^skipped_invoice/$', skipped_invoice, name='skipped_invoice'),
    url(r'^take_collection/$', take_collection, name='take_collection'),
    url(r'^take_cash_collection/$', take_cash_collection, name='take_cash_collection'),

    url(r'^get_today_collection_by_company/$', get_today_collection_by_company, name='get_today_collection_by_company'),
    url(r'^get_today_cash_collection_by_company/$', get_today_cash_collection_by_company,
        name='get_today_cash_collection_by_company'),
    url(r'^add_party_from_sales/$', add_party_from_sales, name='add_party_from_sales'),
    url(r'^get_buyer_list/$', get_buyer_list, name='get_buyer_list'),

    url(r'^change_password_for_sales_user/$', change_password_for_sales_user, name='change_password_for_sales_user'),
    url(r'^get_last_three_invoices/$', get_last_three_invoices, name='get_last_three_invoices'),
    url(r'^generate_collection_report_admin/$', generate_collection_report_admin,
        name='generate_collection_report_admin'),

    url(r'^generate_collection_report_accounts/$', generate_collection_report_accounts,
        name='generate_collection_report_accounts'),
    url(r'^generate_collection_report_supplier/$', generate_collection_report_supplier,
        name='generate_collection_report_supplier'),
    url(r'^generate_collection_report/$', generate_collection_report, name='generate_collection_report'),

    # Accountant
    url(r'^collection_report_accountant/$', collection_report_accountant, name='collection_report_accountant'),

    # Return
    url(r'^return_collection_post/$', return_collection, name='return_collection'),
    url(r'^get_today_return_by_company/$', get_today_return_by_company, name='get_today_return_by_company'),
    url(r'^edit_return/$', edit_return, name='edit_return'),
    url(r'^delete_return_api/$', delete_return_api, name='delete_return_api'),

    # Commission
    url(r'^commission_collection_post/$', commission_collection, name='commission_collection'),
    url(r'^get_today_commission_by_company/$', get_today_commission_by_company, name='get_today_commission_by_company'),
    url(r'^edit_commission/$', edit_commission, name='edit_commission'),
    url(r'^delete_commission_api/$', delete_commission_api, name='delete_commission_api'),

    # Correction
    url(r'^correction_collection_post/$', correct_collection, name='correct_collection'),
    url(r'^get_today_correction_by_company/$', get_today_correction_by_company, name='get_today_correction_by_company'),
    url(r'^edit_correction/$', edit_correction, name='edit_correction'),
    url(r'^delete_correction_api/$', delete_correction_api, name='delete_correction_api'),

    # expense
    url(r'^add_expense/$', add_expense, name='add_expense'),
    url(r'^get_today_expense_by_company/$', get_today_expense_by_company, name='get_today_expense_by_company'),
    url(r'^edit_expense/$', edit_expense, name='edit_expense'),
    url(r'^delete_expense_api/$', delete_expense_api, name='delete_expense_api'),

    url(r'^add_closing_balance_api/$', add_closing_balance_api, name='add_closing_balance_api'),

    # staffAdvance
    url(r'^staff_advance_post/$', staff_advance_post, name='staff_advance_post'),
    url(r'^get_today_staff_advance_by_company/$', get_today_staff_advance_by_company,
        name='get_today_staff_advance_by_company'),
    url(r'^edit_staff_advance/$', edit_staff_advance, name='edit_staff_advance'),
    url(r'^delete_staff_advance_api/$', delete_staff_advance_api, name='delete_staff_advance_api'),

    # Take order PDF
    url(r'^share_order_to_whatsapp_pdf/$', share_order_to_whatsapp_pdf, name='share_order_to_whatsapp_pdf'),
    url(r'^generate_order_report_admin/$', generate_order_report_admin, name='generate_order_report_admin'),
    url(r'^generate_order_report_manager/$', generate_order_report_manager, name='generate_order_report_manager'),

    url(r'^edit_invoice_by_accountant/$', edit_invoice_by_accountant, name='edit_invoice_by_accountant'),



]

mamtaApp/api/urls.py
from django.conf.urls import url
from rest_framework_jwt.views import ObtainJSONWebToken
from .views import *

urlpatterns = [

    url(r'^StaffLogin/$', ObtainJSONWebToken.as_view(serializer_class=StaffLogin)),
    url(r'^GetStaffDetail/$', StaffDetailView.as_view(), name='StaffDetailView'),

    url(r'^BuyerList/$', BuyerListView.as_view(), name='BuyerListView'),
    url(r'^CollectMoneyPost/$', CollectMoneyPostView.as_view(), name='CollectMoneyPostView'),
    url(r'^CollectMoneyList/$', CollectMoneyListView.as_view(), name='CollectMoneyListView'),
    url(r'^ChangePasswordForStaff/$', ChangePasswordPostView.as_view(), name='ChangePasswordPostView'),
    url(r'^CanTakePayment/$', CanTakePaymentView.as_view(), name='CanTakePaymentView'),

]

mamtaApp/urls.py
from django.conf.urls import url
from .views import *



urlpatterns = [
    # buyer
    url(r'^InvoicePrintListJson/$', InvoicePrintListJson.as_view(), name='InvoicePrintListJson'),
    url(r'^LoginListJson/$', LoginListJson.as_view(), name='LoginListJson'),
    url(r'^LogoutListJson/$', LogoutListJson.as_view(), name='LogoutListJson'),
    url(r'^buyerList/$', BuyerListJson.as_view(), name='BuyerListJson'),
    url(r'^ManageCreditListJson/$', ManageCreditListJson.as_view(), name='ManageCreditListJson'),
    url(r'^CreditListJson/$', CreditListJson.as_view(), name='CreditListJson'),
    url(r'^DebitListJson/$', DebitListJson.as_view(), name='DebitListJson'),
    url(r'^CollectionListCashJson/$', CollectionListCashJson.as_view(), name='CollectionListCashJson'),
    url(r'^CollectionListChequeJson/$', CollectionListChequeJson.as_view(), name='CollectionListChequeJson'),
    url(r'^ManageCompanyListJson/$', ManageCompanyListJson.as_view(), name='ManageCompanyListJson'),
    url(r'^StaffListJson/$', StaffListJson.as_view(), name='StaffListJson'),
    url(r'^SupplierCollectionListJson/$', SupplierCollectionListJson.as_view(), name='SupplierCollectionListJson'),
    url(r'^SupplierInvoiceCollectionListJson/$', SupplierInvoiceCollectionListJson.as_view(), name='SupplierInvoiceCollectionListJson'),
    url(r'^SupplierCollectionListCashJson/$', SupplierCollectionListCashJson.as_view(), name='SupplierCollectionListCashJson'),
    url(r'^SupplierCollectionAdminListCashJson/$', SupplierCollectionAdminListCashJson.as_view(), name='SupplierCollectionAdminListCashJson'),
    url(r'^SupplierCollectionListChequeJson/$', SupplierCollectionListChequeJson.as_view(), name='SupplierCollectionListChequeJson'),
    url(r'^SupplierCollectionAdminListChequeJson/$', SupplierCollectionAdminListChequeJson.as_view(), name='SupplierCollectionAdminListChequeJson'),
    url(r'^SupplierCollectionInvoiceList/$', SupplierCollectionInvoiceList.as_view(),
        name='SupplierCollectionInvoiceList'),

    url(r'^SupplierCollectionInvoiceListAdmin/$', SupplierCollectionInvoiceListAdmin.as_view(),
        name='SupplierCollectionInvoiceListAdmin'),

    url(r'^$', home, name='home'),
    # staff
    url(r'^staff/$', staff, name='staff'),
    url(r'^staff/add/$', add_staff, name='add_staff'),
    url(r'^staff/detail/(?P<id>\d+)/$', detail_staff, name='detail_staff'),
    url(r'^staff/edit/(?P<id>\d+)/$', edit_staff, name='edit_staff'),

    # staff api
    url(r'^staff/add/api/$', add_staff_user_api, name='add_staff_user_api'),
    url(r'^staff/edit/api/$', edit_staff_user_api, name='edit_staff_user_api'),
    url(r'^staff/photo_edit/api/$', edit_staff_photo_api, name='edit_staff_photo_api'),
    url(r'^staff/idproof_edit/api/$', edit_staff_idproof_api, name='edit_staff_idproof_api'),
    url(r'^staff/delete/api/$', delete_staff_user_api, name='delete_staff_user_api'),

    # buyers
    url(r'^buyers/$', buyers, name='buyers'),
    url(r'^buyers/add/$', add_buyer, name='add_buyer'),
    url(r'^buyers/detail/(?P<id>\d+)/$', detail_buyer, name='detail_buyer'),
    url(r'^buyers/edit/(?P<id>\d+)/$', edit_buyer, name='edit_buyer'),

    # buyers api
    url(r'^buyers/add/api/$', add_buyer_api, name='add_buyer_api'),
    url(r'^buyers/edit/api/$', edit_buyer_api, name='edit_buyer_api'),
    url(r'^buyers/delete/api/$', delete_buyer_api, name='delete_buyer_api'),

    # credits
    url(r'^buyers/credit/add/api/$', add_money_to_be_collected_api, name='add_money_to_be_collected_api'),

    # report
    url(r'^report/$', report, name='report'),
    # report
    url(r'^manage_credits/$', manage_credits, name='manage_credits'),

    # login
    url(r'^login/$', loginApp, name='loginApp'),

    # logout
    url(r'^Logout/$', logout_user, name='logout'),

    # profile
    url(r'^profile/$', profile, name='profile'),
    url(r'^change_password/$', change_password_api, name='change_password_api'),


    url(r'^manage_company/$', manage_company, name='manage_company'),
    url(r'^add_company_api/$', add_company_api, name='add_company_api'),
    url(r'^edit_company_api/$', edit_company_api, name='edit_company_api'),


    #supply
    url(r'^supplyHome/$', supply_home, name='supply_home'),
    url(r'^supplier_collection_report/$', supplier_collection_report, name='supplier_collection_report'),
    url(r'^take_collection_supplier_api/$', take_collection_supplier_api, name='take_collection_supplier_api'),
    url(r'^take_collection_invoice_supplier_api/$', take_collection_invoice_supplier_api, name='take_collection_invoice_supplier_api'),
    url(r'^edit_collection_supplier_api/$', edit_collection_supplier_api, name='edit_collection_supplier_api'),
    url(r'^approve_collection_supplier_api/$', approve_collection_supplier_api, name='approve_collection_supplier_api'),
    url(r'^approve_collection_supplier_invoice_api/$', approve_collection_supplier_invoice_api, name='approve_collection_supplier_invoice_api'),
    url(r'^delete_collection_supplier_api/$', delete_collection_supplier_api, name='delete_collection_supplier_api'),
    url(r'^delete_collection_supplier_invoice_api/$', delete_collection_supplier_invoice_api, name='delete_collection_supplier_invoice_api'),
    url(r'^cancel_collection_supplier_api/$', cancel_collection_supplier_api, name='cancel_collection_supplier_api'),

    # username exist?
    url(r'^user_name_exist/$', user_name_exist, name='user_name_exist'),

    # login logout report
    url(r'^login_and_logout_report/$', login_and_logout_report, name='login_and_logout_report'),

    #cashier
    url(r'^cashierHome/$', cashier_home, name='cashier_home'),

    #print Report
    url(r'^print_report/$', print_report, name='print_report'),

    # Order Team
    url(r'^order_list_admin/$', order_list_admin, name='order_list_admin'),
    url(r'^order_home/$', order_home, name='order_home'),
    url(r'^order_manager_home/$', order_manager_home, name='order_manager_home'),
    url(r'^assigned_stock_group_to_manager/$', assigned_stock_group_to_manager, name='assigned_stock_group_to_manager'),
    url(r'^assigned_staff_to_manager/$', assigned_staff_to_manager, name='assigned_staff_to_manager'),
    url(r'^manage_order_managers/$', manage_order_managers, name='manage_order_managers'),
    url(r'^api/take_order_api/$', take_order_api, name='take_order_api'),
    url(r'^api/add_staff_to_manager_api/$', add_staff_to_manager_api, name='add_staff_to_manager_api'),
    url(r'^api/edit_staff_to_manager_api/$', edit_staff_to_manager_api, name='edit_staff_to_manager_api'),
    url(r'^api/delete_assign_manager_staff_user_api/$', delete_assign_manager_staff_user_api, name='delete_assign_manager_staff_user_api'),
    url(r'^api/OrderListByUserPerDayJson/$', OrderListByUserPerDayJson.as_view(), name='OrderListByUserPerDayJson'),
    url(r'^api/OrderListAdminJson/$', OrderListAdminJson.as_view(), name='OrderListAdminJson'),
    url(r'^api/OrderListManagerJson/$', OrderListManagerJson.as_view(), name='OrderListManagerJson'),
    url(r'^api/ManagerAssignedListJson/$', ManagerAssignedListJson.as_view(), name='ManagerAssignedListJson'),
    url(r'^api/MyManagerAssignedStaffListJson/$', MyManagerAssignedStaffListJson.as_view(), name='MyManagerAssignedStaffListJson'),

    url(r'^manage_order_group/$', manage_order_group, name='manage_order_group'),
    url(r'^manage_stock_group_managers/$', manage_stock_group_managers, name='manage_stock_group_managers'),
    url(r'^api/add_stock_group_api/$', add_stock_group_api, name='add_stock_group_api'),
    url(r'^api/edit_stock_group_api/$', edit_stock_group_api, name='edit_stock_group_api'),
    url(r'^api/StockGroupListJson/$', StockGroupListJson.as_view(), name='StockGroupListJson'),
    url(r'^api/add_stock_group_to_manager_api/$', add_stock_group_to_manager_api, name='add_stock_group_to_manager_api'),
    url(r'^api/edit_stock_group_to_manager_api/$', edit_stock_group_to_manager_api, name='edit_stock_group_to_manager_api'),
    url(r'^api/delete_assign_manager_stock_group_api/$', delete_assign_manager_stock_group_api, name='delete_assign_manager_stock_group_api'),
    url(r'^api/ManagerStockGroupAssignedListJson/$', ManagerStockGroupAssignedListJson.as_view(), name='ManagerStockGroupAssignedListJson'),
    url(r'^api/MyManagerAssignedStockGroupListJson/$', MyManagerAssignedStockGroupListJson.as_view(), name='MyManagerAssignedStockGroupListJson'),

]

mamtaPro/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("mamtaApp.urls", namespace='mamtaApp')),
    url(r'^invoice/', include("invoice.urls", namespace='invoiceApp')),
    url(r'^attendance/', include("attendance.urls", namespace='attendanceApp')),
    url(r'^api/', include('mamtaApp.api.urls')),
    url(r'^invoiceApi/', include('invoice.api.urls')),
    url(r'^docs/', include('rest_framework_docs.urls')),
    url('', include('pwa.urls')),
]
handler404 = 'mamtaApp.views.bad_request'
handler500 = 'mamtaApp.views.bad_server'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mamtaApp/templates/mamtaApp/order/assignedStaffToManagers.html
{% extends 'mamtaApp/index.html' %}
{% load staticfiles %}
{% block body %}
    <style>
        .zoom {

            transition: transform .2s; /* Animation */
            width: 30px;
            height: 30px;
            margin: 0 auto;
        }

        .zoom:hover {
            transform: scale(4); /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
        }

        .card {
            background: #fff;
            min-height: 50px;
            box-shadow: 0 0px 0px rgba(0, 0, 0, 0) !important;
            position: relative;
            margin-bottom: 30px;
            -webkit-border-radius: 2px;
            -moz-border-radius: 2px;
            -ms-border-radius: 2px;
            border-radius: 2px;
        }

    </style>

    <section class="content">

            <!-- Striped Rows -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="padding-right: 0;padding-left: 0">
                    <div class="card">
                        <div class="header">
                            <h2>
                                ASSIGNED STAFF LIST
                            </h2>
                        </div>
                        <div class="body table-responsive">
                            <table id="buyerCreditTable" class="table table-bordered table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>StaffName</th>
                                    <th>AddedOn</th>
                                </tr>
                                </thead>
                                <tbody>

                                </tbody>
                                  <tfoot>
                                     <tr>
                                     <th>#</th>
                                    <th>StaffName</th>
                                    <th>AddedOn</th>
                                </tr>
                                    </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Striped Rows -->
        </div>
    </section>
    <div class="modal fade" id="ChangePasswordModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content" style="background-color: lightgrey;">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="exampleModalLabel">Change Password</h4>
                </div>
                <form id="PasswordForm"> {% csrf_token %}
                    <div class="modal-body">

                        <div class="form-group">
                            <label for="nPass" class="control-label">New Password: <span
                                    style="color: grey;font-size: 10px;"> Note - Password should be at least 5 character long.</span></label>
                            <input autocomplete="off" type="password" class="form-control" id="nPass">
                        </div>
                        <div class="form-group">
                            <label for="rPass" class="control-label">Confirm New Password:</label>
                            <input autocomplete="off" type="password" class="form-control" id="rPass">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" onclick="ChangePassword()">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <ul style="    position: fixed;top: 20px;right: 20px;padding-bottom: 20px;z-index: 100; text-align: center">
        <a href="{% url 'mamtaApp:logout' %}"
           style="width:100%;padding-right: 10px;background-color: #3aabfb!important; color: white!important;"
           type="button" class="btn ">Logout</a>
        <a style="color: white;font-size: 13px;cursor: pointer;" data-toggle="modal"
           data-target="#ChangePasswordModal"
           data-whatever="@mdo">
            <strong>Change Password</strong>
        </a>
    </ul>
{% endblock %}
{% block js %}
<script src="{% static 'js/pages/ui/modals.js' %}"></script>

    <script>
        $(document).ready(function () {
            $('#buyerCreditTable').dataTable({
                dom: 'Blfrtip',
                buttons: ['excel', 'print'
                ],
                "columnDefs": [
                    {"name": "id", "targets": 0, "orderable": false},
                    {"name": "staffID", "targets": 1, "orderable": true},
                    {"name": "datetime", "targets": 2, "orderable": true},

                ],
                aaSorting: [[1, 'asc']],
                "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                "pageLength": 10,
                "processing": true,
                "serverSide": true,
                "ajax": "{% url 'mamtaApp:MyManagerAssignedStaffListJson' %}"
            });
        });
       function ChangePassword() {
            var nPass = $('#nPass').val();
            var rPass = $('#rPass').val();


            data = new FormData();
            data.append('nPass', nPass);

            if (nPass === "" || rPass === "") {
                $('#name_status').addClass('validate_data');
                $('#name_status').html('Fields are required.').fadeIn().fadeOut(2000);

            }
            else if (nPass != rPass) {
                $('#name_status').addClass('validate_data');
                $('#name_status').html('Password not matched. Please try again.').fadeIn().fadeOut(2000);

            }
            else if (nPass.length < 5) {
                $('#name_status').addClass('validate_data');
                $('#name_status').html('Password should be atleast 5 character long.').fadeIn().fadeOut(2000);

            }

            else {
                $.ajax({
                    type: 'post',
                    url: '{% url 'invoiceApp:change_password_for_sales_user' %}',
                    data: data,
                    contentType: false,
                    cache: false,
                    processData: false,


                    success: function (response) {
                        if (response.message === 'success') {
                            $('#name_status').addClass('validate_data');
                            $('#name_status').html('Password Changed Successfully').fadeIn().fadeOut(2000);
                            $('#PasswordForm')[0].reset();
                            $('#ChangePasswordModal').modal('hide');

                        }

                        else {
                            $('#name_status').addClass('validate_data');
                            $('#name_status').html('error').fadeIn().fadeOut(2000);
                        }

                    },
                    error: function () {
                        $('#name_status').addClass('validate_data');
                        $('#name_status').html('error.').fadeIn().fadeOut(2000);
                    }
                });
            }

        }

    </script>

{% endblock %}